import "dotenv/config";
import { prisma } from "../src/lib/prisma";

const packages = [
  // ─── TOURS ───────────────────────────────────────────────────────────────
  {
    slug: "patagonia-wilderness-trek",
    title: "Patagonia Wilderness Trek",
    category: "tours",
    description:
      "Multi-day guided trek through Torres del Paine with glacier views and premium lodges.",
    longDescription:
      "Experience the raw beauty of Patagonia on this expertly guided expedition. Cross iconic trails, camp under southern skies, and explore glaciers with certified mountain guides. Designed for adventurous travelers who want comfort without sacrificing wilderness authenticity. Days balance challenging hikes with lodge recovery, so you stay strong for the final high viewpoints.",
    destination: "Chile — Patagonia",
    duration: "8 days / 7 nights",
    difficulty: "Moderate",
    priceUsd: 3200,
    depositPercent: 30,
    maxGuests: 10,
    imageUrl: "https://images.unsplash.com/photo-1518091464577-65227db406a6?w=1200&q=80",
    highlights: JSON.stringify([
      "Torres del Paine circuit highlights",
      "Professional English-speaking guides",
      "Lodge and eco-camp accommodation",
      "All meals and park permits included",
      "Glacier viewpoint day with safety briefing",
    ]),
    included: JSON.stringify([
      "Airport transfers",
      "Accommodation",
      "All meals",
      "Park fees",
      "Guide services",
    ]),
    excluded: JSON.stringify(["International flights", "Travel insurance", "Personal gear"]),
    featured: true,
    sortOrder: 1,
  },
  {
    slug: "scandinavian-fjord-expedition",
    title: "Scandinavian Fjord Expedition",
    category: "tours",
    description:
      "Sail and hike Norway's fjords with wildlife watching and coastal village stays.",
    longDescription:
      "A premium nature tour combining fjord cruising, coastal hiking, and authentic Nordic culture. Perfect for international travelers seeking scenic adventure without extreme physical demands. Stay in boutique coastal hotels, board private boats into narrow inlets, and walk cliff-edge trails with local naturalists.",
    destination: "Norway — Western Fjords",
    duration: "6 days / 5 nights",
    difficulty: "Easy",
    priceUsd: 2450,
    depositPercent: 30,
    maxGuests: 14,
    imageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80",
    highlights: JSON.stringify([
      "Private fjord boat excursions",
      "Puffin and eagle watching",
      "Historic fishing villages",
      "Comfortable boutique hotels",
    ]),
    included: JSON.stringify(["Boat trips", "Hotels", "Breakfast & lunch", "Local guides"]),
    excluded: JSON.stringify(["Flights", "Dinner (except day 1)", "Alcoholic beverages"]),
    featured: true,
    sortOrder: 2,
  },
  {
    slug: "japanese-alps-cultural-trek",
    title: "Japanese Alps Cultural Trek",
    category: "tours",
    description:
      "Mountain trails, onsen towns, and alpine villages across the Japanese Northern Alps.",
    longDescription:
      "Combine scenic ridge walks with deep cultural immersion in the Japanese Alps. Hike between mountain huts and traditional ryokan, soak in natural hot springs after each day on the trail, and taste seasonal mountain cuisine. Ideal for travelers who want nature and culture in equal measure.",
    destination: "Japan — Northern Alps",
    duration: "7 days / 6 nights",
    difficulty: "Moderate",
    priceUsd: 2900,
    depositPercent: 30,
    maxGuests: 12,
    imageUrl: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    highlights: JSON.stringify([
      "Guided alpine day hikes",
      "Traditional ryokan stays",
      "Onsen recovery evenings",
      "Seasonal kaiseki dinners",
      "Local English-speaking guides",
    ]),
    included: JSON.stringify([
      "Accommodation",
      "Most meals",
      "Guided hikes",
      "Onsen access",
      "Domestic transfers on itinerary",
    ]),
    excluded: JSON.stringify(["International flights", "Travel insurance", "Personal gear"]),
    featured: true,
    sortOrder: 3,
  },
  {
    slug: "morocco-atlas-desert-circuit",
    title: "Morocco Atlas & Desert Circuit",
    category: "tours",
    description:
      "High Atlas villages, kasbahs, and a Sahara camp under the stars.",
    longDescription:
      "A classic Morocco overland circuit linking the High Atlas mountains with the edge of the Sahara. Walk village paths with local hosts, explore historic kasbahs, and sleep in a private desert camp. Balanced pacing suits first-time visitors and returning travelers alike.",
    destination: "Morocco — Atlas & Sahara",
    duration: "8 days / 7 nights",
    difficulty: "Easy",
    priceUsd: 2100,
    depositPercent: 30,
    maxGuests: 12,
    imageUrl: "https://images.unsplash.com/photo-1489749798305-4fea3ae63d43?w=1200&q=80",
    highlights: JSON.stringify([
      "High Atlas village walks",
      "Private Sahara camp night",
      "Kasbah and medina visits",
      "4×4 desert transfer",
      "Expert local driver-guides",
    ]),
    included: JSON.stringify([
      "Private transport",
      "Hotels & desert camp",
      "Daily breakfast",
      "Selected dinners",
      "Guide services",
    ]),
    excluded: JSON.stringify(["Flights", "Travel insurance", "Optional camel trek tips"]),
    featured: false,
    sortOrder: 4,
  },

  // ─── HUNTING ─────────────────────────────────────────────────────────────
  {
    slug: "red-stag-scotland-hunt",
    title: "Scottish Red Stag Hunt",
    category: "hunting",
    description:
      "Premium red stag hunt on a private Highland estate with professional stalker and lodge.",
    longDescription:
      "A classic European hunting experience on managed Highland grounds. Includes estate stalker, rifle rental option, field dressing support, and full-board lodge accommodation. All permits arranged through licensed local partners. Ideal for international hunters seeking a refined, well-managed red stag package.",
    destination: "Scotland — Highlands",
    duration: "5 days / 4 nights",
    difficulty: "Intermediate",
    species: "Red Stag",
    priceUsd: 4800,
    depositPercent: 30,
    maxGuests: 4,
    imageUrl: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1200&q=80",
    highlights: JSON.stringify([
      "Private estate access",
      "Licensed stalker & ghillie",
      "Trophy preparation support",
      "Luxury hunting lodge",
      "Rifle rental available",
    ]),
    included: JSON.stringify([
      "Estate fees",
      "Stalker services",
      "Lodge full board",
      "Field dressing",
      "Permit assistance",
    ]),
    excluded: JSON.stringify([
      "Trophy fee (species dependent)",
      "Rifle import permit",
      "Taxidermy & shipping",
      "Gratuities",
    ]),
    featured: true,
    sortOrder: 1,
  },
  {
    slug: "wild-boar-balkans-hunt",
    title: "Balkan Wild Boar Hunt",
    category: "hunting",
    description:
      "Night and day wild boar hunting with local outfitter, mountain lodge, and translator.",
    longDescription:
      "Organized wild boar hunting in the Balkan mountains with experienced local outfitters. Suitable for international hunters seeking an affordable European driven and stalking combination hunt. Includes lodge stay, meals, and on-ground support with translator.",
    destination: "Serbia — Balkan Mountains",
    duration: "4 days / 3 nights",
    difficulty: "Intermediate",
    species: "Wild Boar",
    priceUsd: 2650,
    depositPercent: 30,
    maxGuests: 6,
    imageUrl: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=1200&q=80",
    highlights: JSON.stringify([
      "Day and night hunting stands",
      "Local outfitter & translator",
      "Mountain lodge accommodation",
      "Weapon rental available",
    ]),
    included: JSON.stringify([
      "Outfitter services",
      "Hunting license support",
      "Accommodation",
      "Meals",
      "Ground transport on site",
    ]),
    excluded: JSON.stringify(["Trophy fees", "Ammo", "Flights", "Export documents"]),
    featured: true,
    sortOrder: 2,
  },
  {
    slug: "namibia-plains-game-safari",
    title: "Namibia Plains Game Safari",
    category: "hunting",
    description:
      "Free-range plains game hunt with PH, trackers, and lodge safari camp in Namibia.",
    longDescription:
      "A classic African plains game safari on free-range concession land. Hunt with a professional hunter and experienced trackers from a comfortable lodge camp. Species opportunities typically include springbok, gemsbok, kudu, and warthog depending on season and permit. Ideal for hunters adding Africa to their portfolio.",
    destination: "Namibia — Free-range concession",
    duration: "7 days / 6 nights",
    difficulty: "Intermediate",
    species: "Plains Game",
    priceUsd: 6200,
    depositPercent: 30,
    maxGuests: 4,
    imageUrl: "https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1200&q=80",
    highlights: JSON.stringify([
      "Professional hunter & trackers",
      "Free-range concession",
      "Safari lodge camp",
      "Trophy care support",
      "Airport transfers in-country",
    ]),
    included: JSON.stringify([
      "PH and tracking team",
      "Lodge full board",
      "Field preparation",
      "Vehicle & fuel on hunt",
      "License assistance",
    ]),
    excluded: JSON.stringify([
      "Trophy fees",
      "Taxidermy & shipping",
      "International flights",
      "Ammo",
    ]),
    featured: true,
    sortOrder: 3,
  },
  {
    slug: "new-zealand-red-deer-hunt",
    title: "New Zealand Red Deer Hunt",
    category: "hunting",
    description:
      "High-country red deer hunt with helicopter access option and alpine lodge base.",
    longDescription:
      "Hunt free-range red deer in New Zealand's dramatic high country with an experienced guide. Package includes lodge base, ground stalking, and optional helicopter access (quoted separately when requested). Excellent for hunters seeking a Southern Hemisphere classic with stunning scenery.",
    destination: "New Zealand — South Island",
    duration: "5 days / 4 nights",
    difficulty: "Advanced",
    species: "Red Deer",
    priceUsd: 5400,
    depositPercent: 30,
    maxGuests: 4,
    imageUrl: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200&q=80",
    highlights: JSON.stringify([
      "High-country free-range hunt",
      "Experienced NZ guide",
      "Alpine lodge base",
      "Optional heli-access day",
      "Trophy care assistance",
    ]),
    included: JSON.stringify([
      "Guide services",
      "Lodge accommodation",
      "Meals",
      "Ground transport",
      "Permit support",
    ]),
    excluded: JSON.stringify([
      "Helicopter time",
      "Trophy fees if applicable",
      "Flights",
      "Taxidermy",
    ]),
    featured: false,
    sortOrder: 4,
  },

  // ─── SURVIVAL ────────────────────────────────────────────────────────────
  {
    slug: "arctic-bushcraft-program",
    title: "Arctic Bushcraft Skills Program",
    category: "survival",
    description:
      "Hands-on wilderness skills training: shelter, fire, navigation, and cold-weather survival.",
    longDescription:
      "A structured survival training program led by certified wilderness instructors. Learn essential bushcraft and cold-climate survival skills in a controlled, progressive environment. No gamification — pure professional outdoor training suitable for serious adventure travelers and expedition prep.",
    destination: "Finland — Lapland",
    duration: "5 days / 4 nights",
    difficulty: "Advanced",
    priceUsd: 1850,
    depositPercent: 30,
    maxGuests: 8,
    imageUrl: "https://images.unsplash.com/photo-1483728642387-6c3bdd6c93e5?w=1200&q=80",
    highlights: JSON.stringify([
      "Certified wilderness instructors",
      "Shelter building & fire craft",
      "Arctic navigation training",
      "Emergency first aid module",
      "Completion certificate",
    ]),
    included: JSON.stringify([
      "Instruction",
      "Base camp accommodation",
      "Meals",
      "Core survival kit rental",
      "Certificate of completion",
    ]),
    excluded: JSON.stringify([
      "Personal cold-weather clothing",
      "Flights",
      "Insurance",
      "Optional private gear",
    ]),
    featured: true,
    sortOrder: 1,
  },
  {
    slug: "jungle-survival-expedition",
    title: "Amazon Jungle Survival Expedition",
    category: "survival",
    description:
      "Intensive jungle survival course: water sourcing, shelter, navigation, and rescue protocols.",
    longDescription:
      "Train with veteran jungle guides in the Amazon basin. This program covers hydration, shelter construction, wildlife awareness, and emergency signaling. Designed for adventurers preparing for serious expeditions who want professional instruction in a real jungle environment.",
    destination: "Peru — Amazon Basin",
    duration: "7 days / 6 nights",
    difficulty: "Advanced",
    priceUsd: 2400,
    depositPercent: 30,
    maxGuests: 6,
    imageUrl: "https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=1200&q=80",
    highlights: JSON.stringify([
      "Veteran jungle guides",
      "Water purification training",
      "Emergency signaling drills",
      "River extraction protocols",
    ]),
    included: JSON.stringify([
      "Guide team",
      "Camping equipment",
      "Meals in field",
      "River transport",
      "Safety equipment",
    ]),
    excluded: JSON.stringify(["Flights to Iquitos", "Vaccinations", "Personal kit", "Insurance"]),
    featured: true,
    sortOrder: 2,
  },
  {
    slug: "alpine-mountain-survival",
    title: "Alpine Mountain Survival Course",
    category: "survival",
    description:
      "High-mountain survival skills: rope safety, weather reading, bivouac, and rescue basics.",
    longDescription:
      "A professional alpine survival course in the European Alps. Learn mountain weather assessment, emergency bivouac construction, basic rope systems, and self-rescue fundamentals with IFMGA-aware instructors. Perfect preparation for serious mountain travel.",
    destination: "Switzerland — Alps",
    duration: "5 days / 4 nights",
    difficulty: "Advanced",
    priceUsd: 2150,
    depositPercent: 30,
    maxGuests: 8,
    imageUrl: "https://images.unsplash.com/photo-1454496522488-7a8e488e8606?w=1200&q=80",
    highlights: JSON.stringify([
      "Mountain weather & decision-making",
      "Emergency bivouac skills",
      "Basic rope & belay systems",
      "Self-rescue fundamentals",
      "Mountain hut nights",
    ]),
    included: JSON.stringify([
      "Instruction",
      "Hut accommodation",
      "Meals",
      "Group safety equipment",
      "Certificate of completion",
    ]),
    excluded: JSON.stringify([
      "Personal alpine clothing",
      "Flights",
      "Insurance",
      "Technical boots (rental available)",
    ]),
    featured: true,
    sortOrder: 3,
  },
  {
    slug: "desert-survival-wadi-rum",
    title: "Desert Survival Challenge — Wadi Rum",
    category: "survival",
    description:
      "Desert navigation, water discipline, shelter, and night travel in Jordan's Wadi Rum.",
    longDescription:
      "A focused desert survival program in Wadi Rum with Bedouin instructors and professional safety oversight. Train water discipline, shade shelters, solar navigation, and night movement in a controlled desert setting. Camp under clear desert skies between skill modules.",
    destination: "Jordan — Wadi Rum",
    duration: "4 days / 3 nights",
    difficulty: "Intermediate",
    priceUsd: 1650,
    depositPercent: 30,
    maxGuests: 10,
    imageUrl: "https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=1200&q=80",
    highlights: JSON.stringify([
      "Bedouin instructor team",
      "Water discipline & rationing",
      "Desert shelter systems",
      "Night navigation module",
      "Desert camp stays",
    ]),
    included: JSON.stringify([
      "Instruction",
      "Desert camp",
      "Meals",
      "Ground transfers in Wadi Rum",
      "Safety support vehicle",
    ]),
    excluded: JSON.stringify(["Flights to Amman", "Travel insurance", "Personal desert kit"]),
    featured: false,
    sortOrder: 4,
  },
];

async function main() {
  for (const pkg of packages) {
    await prisma.package.upsert({
      where: { slug: pkg.slug },
      update: pkg,
      create: pkg,
    });
  }
  console.log(`Seeded ${packages.length} packages`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
